### ISSUE TITLE
can not execute trainer.run()

### ISSUE THREAD

**Issue by s1sun** [kiryor/NNPUlearning#3]
>>> trainer.run()
epoch       train/nnPU/error  test/nnPU/error  train/uPU/error  test/uPU/error  elapsed_time
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sesun/anaconda3/lib/python3.6/site-packages/chainer/training/trainer.py", line 299, in run
    entry.extension(self)
  File "/home/sesun/anaconda3/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py", line 137, in __call__
    result = self.evaluate()
  File "<stdin>", line 23, in evaluate
  File "<stdin>", line 23, in <dictcomp>
NameError: name 'np' is not defined

Could you please tell me what causes the problem? Thanks.

**Comment by pollenjp** [comment]
Work well by inserting import line as below into the top of `train.py`.
```
import numpy as np
```

**Comment by s1sun** [comment]
insert below line into train.py
import numpy as np

**Comment by pollenjp** [comment]
@s1sun 

not work? If work, close this issue.

**Comment by s1sun** [comment]
works fine.
